package com.isaac.easy.mysqldbsample.mall.module;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_delivery
 */
public class MallDelivery {
    /**
     * Database Column Remarks:
     *   主键ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_delivery.id
     *
     * @mbg.generated Tue Dec 01 17:10:55 CST 2020
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_delivery.account_id
     *
     * @mbg.generated Tue Dec 01 17:10:55 CST 2020
     */
    private Long accountId;

    /**
     * Database Column Remarks:
     *   用户地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_delivery.address
     *
     * @mbg.generated Tue Dec 01 17:10:55 CST 2020
     */
    private String address;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_delivery.create_time
     *
     * @mbg.generated Tue Dec 01 17:10:55 CST 2020
     */
    private Long createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_delivery.id
     *
     * @return the value of t_delivery.id
     *
     * @mbg.generated Tue Dec 01 17:10:55 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_delivery.id
     *
     * @param id the value for t_delivery.id
     *
     * @mbg.generated Tue Dec 01 17:10:55 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_delivery.account_id
     *
     * @return the value of t_delivery.account_id
     *
     * @mbg.generated Tue Dec 01 17:10:55 CST 2020
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_delivery.account_id
     *
     * @param accountId the value for t_delivery.account_id
     *
     * @mbg.generated Tue Dec 01 17:10:55 CST 2020
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_delivery.address
     *
     * @return the value of t_delivery.address
     *
     * @mbg.generated Tue Dec 01 17:10:55 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_delivery.address
     *
     * @param address the value for t_delivery.address
     *
     * @mbg.generated Tue Dec 01 17:10:55 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_delivery.create_time
     *
     * @return the value of t_delivery.create_time
     *
     * @mbg.generated Tue Dec 01 17:10:55 CST 2020
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_delivery.create_time
     *
     * @param createTime the value for t_delivery.create_time
     *
     * @mbg.generated Tue Dec 01 17:10:55 CST 2020
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}