package com.isaac.easy.mysqldbsample.mall.module;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_product
 */
public class MallProduct {
    /**
     * Database Column Remarks:
     *   主键ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.id
     *
     * @mbg.generated Wed Dec 09 23:14:56 CST 2020
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   商品名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.name
     *
     * @mbg.generated Wed Dec 09 23:14:56 CST 2020
     */
    private String name;

    /**
     * Database Column Remarks:
     *   商品描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.description
     *
     * @mbg.generated Wed Dec 09 23:14:56 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.freeze_count
     *
     * @mbg.generated Wed Dec 09 23:14:56 CST 2020
     */
    private Long freezeCount;

    /**
     * Database Column Remarks:
     *   库存总量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.total
     *
     * @mbg.generated Wed Dec 09 23:14:56 CST 2020
     */
    private Long total;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.create_time
     *
     * @mbg.generated Wed Dec 09 23:14:56 CST 2020
     */
    private Long createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.id
     *
     * @return the value of t_product.id
     *
     * @mbg.generated Wed Dec 09 23:14:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.id
     *
     * @param id the value for t_product.id
     *
     * @mbg.generated Wed Dec 09 23:14:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.name
     *
     * @return the value of t_product.name
     *
     * @mbg.generated Wed Dec 09 23:14:56 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.name
     *
     * @param name the value for t_product.name
     *
     * @mbg.generated Wed Dec 09 23:14:56 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.description
     *
     * @return the value of t_product.description
     *
     * @mbg.generated Wed Dec 09 23:14:56 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.description
     *
     * @param description the value for t_product.description
     *
     * @mbg.generated Wed Dec 09 23:14:56 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.freeze_count
     *
     * @return the value of t_product.freeze_count
     *
     * @mbg.generated Wed Dec 09 23:14:56 CST 2020
     */
    public Long getFreezeCount() {
        return freezeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.freeze_count
     *
     * @param freezeCount the value for t_product.freeze_count
     *
     * @mbg.generated Wed Dec 09 23:14:56 CST 2020
     */
    public void setFreezeCount(Long freezeCount) {
        this.freezeCount = freezeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.total
     *
     * @return the value of t_product.total
     *
     * @mbg.generated Wed Dec 09 23:14:56 CST 2020
     */
    public Long getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.total
     *
     * @param total the value for t_product.total
     *
     * @mbg.generated Wed Dec 09 23:14:56 CST 2020
     */
    public void setTotal(Long total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.create_time
     *
     * @return the value of t_product.create_time
     *
     * @mbg.generated Wed Dec 09 23:14:56 CST 2020
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.create_time
     *
     * @param createTime the value for t_product.create_time
     *
     * @mbg.generated Wed Dec 09 23:14:56 CST 2020
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}