server:
  port: 8080

spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true
      username: mallUser
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      jdbc-url: jdbc:mysql://localhost:3306/mall_slave?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariPool
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: select 1
    # 数据库驱动 测试
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8
    username: root
    password:

mybatis:
  mapper-locations: classpath:dynamicmapper/*.xml