server:
  port: 8081


spring:
  application:
    name: spring-redis
  redis:
    host: 0.0.0.0
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 5
        max-wait: -1
        max-idle: 2
        min-idle: 1

logging:
  level:
    root: debug
    org.springframework.web: info
    org.apache.ibatis: debug
    com.isaac.easy: debug
    io.netty: info
  path: "./logs"