package com.isaac.easy.mysqldbsample.mall.dao.dynamic;

import com.isaac.easy.mysqldbsample.mall.module.MallOrder;
import com.isaac.easy.mysqldbsample.mall.module.MallProduct;
import com.isaac.easy.mysqldbsample.mall.module.MallProductExample;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface MallProductMapper {
    @Update("update t_product set total = total - #{consumeCount}, freeze_count = freeze_count + #{consumeCount} where id = #{productId}")
    int updateTry( MallOrder order );
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Tue Dec 01 17:10:55 CST 2020
     */
    int deleteByPrimaryKey( Long id );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Tue Dec 01 17:10:55 CST 2020
     */
    int insert( MallProduct record );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Tue Dec 01 17:10:55 CST 2020
     */
    int insertSelective( MallProduct record );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Tue Dec 01 17:10:55 CST 2020
     */
    List<MallProduct> selectByExample( MallProductExample example );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Tue Dec 01 17:10:55 CST 2020
     */
    MallProduct selectByPrimaryKey( Long id );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Tue Dec 01 17:10:55 CST 2020
     */
    int updateByPrimaryKeySelective( MallProduct record );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Tue Dec 01 17:10:55 CST 2020
     */
    int updateByPrimaryKey( MallProduct record );
}